### PR TITLE
Add DaLUKE to robustness testing

### PR DESCRIPTION
**Pull request by sorenmulli**
Discussed at https://github.com/peleiden/daluke/issues/105

### CODE REVIEW

**Comment by sorenmulli** [comment]
Most code is shamelessly taken from  `apply_fn_danlp`.

Forward passing and scoring in the `__main__` block worked on my end, though I have not really understood the broader use of the apply function, so I might have missed something.

If you have issues with loading DaLUKE, add the following lines before  `daluke = AutoNERDaLUKE()` to get output (package `pelutils` should be installed as a daluke dep.):
```py
from pelutils import log, Levels
log.configure(print_level=Levels.DEBUG)
```

**Comment by KennethEnevoldsen** [comment]
I will take a look at it. However, as it stands currently this will likely lead to a very slow implementation as you will only be taking one example at a time. This will make the model compare unfavorably based on speed (This is only done for DaNLP as otherwise, we would have to rewrite their wrapper). The NERDA is much faster if you want to take inspiration from it.

**Comment by KennethEnevoldsen** [comment]
The apply function is used in the [score function](https://github.com/centre-for-humanities-computing/DaCy/blob/ccda8a54ba03781cca03eb8ea6b6b82c64b3bb4c/dacy/score/score.py#L43), which applied the model under a variety of specified augmenters. 

I can see that the auto generated docs does not include the score function though, will make sure to fix that.

**Comment by sorenmulli** [comment]
> I will take a look at it. However, as it stands currently this will likely lead to a very slow implementation as you will only be taking one example at a time. This will make the model compare unfavorably based on speed (This is only done for DaNLP as otherwise, we would have to rewrite their wrapper). The NERDA is much faster if you want to take inspiration from it.

Was not aware of speed tests, I have made an issue for a batched inference API wrapper for DaLUKE (https://github.com/peleiden/daluke/issues/111). 
This will probably take a while (vacation without pc 😉). 
When that's done, I'll implement it here, looking at how it's done for NERDA.

**Comment by KennethEnevoldsen** [comment]
Hi @sorenmulli, thanks for these changes. Sorry for the late response. We plan to rerun these tests in the next iteration of DaCy which is planned for the first half of the following year. I will merge the changes now, but the inclusion in the benchmark will come later in the year.

Thanks again for the PR.

**Pull request merged**
