### PR TITLE
Make cache dir configurable

### PR DESCRIPTION
**Pull request by dhpollack**
I would like to make the default cache dir configurable with an environmental variable.  This is a simple PR to allow one to do that with the variable `DACY_CACHE_DIR`.

### CODE REVIEW

**Comment by dhpollack** [comment]
> @dhpollack your colleague's problem might be fixable by setting `open_unverified_connection=True`. The default is `False` for security reasons. You can for example check the [documentation](https://centre-for-humanities-computing.github.io/DaCy/dacy.sentiment.html#dacy.sentiment.wrapped_models.add_bertemotion_emo) of the emotion model for more on this.

Thanks, that option did actually solve the issue for us although if you are not using that on the CI, I would think it is something that should be fixed.  Do you have an idea when the CI will work again and when we could merge this PR?  Currently, I am using a bit of a hack with soft links to simulate this but it's really not a pretty solution.

**Comment by KennethEnevoldsen** [comment]
Extended this PR in another branch and it is thus moved to PR #70. The is a couple of good things I got to add here:

1) The cache dir is now configurable! 🎉
2) I have removed DaNLP as a dependency and now download their models directly from the Huggingface model hub where they were recently added. This has multiple benefits. For your colleague, it means that the `open_unverified_connection` argument is no longer necessary.
3) I removed the readability module, if you or your colleagues use that I highly recommend the [textdescriptives](https://github.com/hlasse/TextDescriptives) package developed @HLasse, and I

Turns out that the bug originated in the new version of spacy-transformers, I have added an issue on this #71, for now, I have now restricted to version numbers of packages to avoid breaking changes.

**Comment by dhpollack** [comment]
@KennethEnevoldsen awesome work!  Yea, we noticed the issue with the dependencies as well and pinned them ourselves.  Also thanks for the help.

Just as a mini-fyi, instead of closing my PR and then opening another with a different target branch, you can click the "Edit" button at the PR and change the target merge branch.  This has the advantage of keeping this discussion linked to the merge commit in the main branch and more importantly let's me have the glory of having a commit in the premiere Danish language NLP library.  :smile:

**Comment by KennethEnevoldsen** [comment]
The edits were a bit more extensive than what would have been possible in an edit. Had to go through a whole debugging session to figure out if the #71 issue was fixable.

However, credit is (extremely) important in open-science communities, therefore my dev branch used a PR (#69 ) from your branch to ensure that you are indeed listed as a contributor to DaCy 🎉:

Screenshot 2021-11-05 at 15 38 25

**Pull request closed without merging**
